### ISSUE TITLE
BED file

### ISSUE THREAD

**Issue by kokyriakidis** [magspho/hifieval#2]
Hi @magspho !

When I use the `-b` option with a BED file I get:

```
Traceback (most recent call last):
  File "/home/kokyriakidis/micromamba/envs/hifieval/bin/hifieval.py", line 697, in <module>
    main(sys.argv)
  File "/home/kokyriakidis/micromamba/envs/hifieval/bin/hifieval.py", line 663, in main
    output = evalbed2dict(*args)
             ^^^^^^^^^^^^^^^^^^^
TypeError: evalbed2dict() takes 3 positional arguments but 7 were given
```

Is there anything I am missing?

**Comment by bpanda-dev** [comment]
@kokyriakidis Could you please mention how you were able to solve this issue?

Thanks
